name: osu-wiki continuous integration

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: markdownlint (changed files)
    runs-on: ubuntu-latest
    steps:
      - name: sparse checkout
        shell: bash
        run: |
          REPOSITORY="https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git"

          git version
          git clone --filter=blob:none --no-checkout ${REPOSITORY} .
          git config --local gc.auto 0

          git sparse-checkout init
          git sparse-checkout set '**/*.md'

          git -c protocol.version=2 fetch --no-tags --prune --progress --depth=2 origin ${{ github.head_ref }} ${{ github.base_ref }}
          git checkout --progress --force -B ${{ github.head_ref }} refs/remotes/origin/${{ github.head_ref }}

      - name: setup node
        uses: actions/setup-node@v1

      - name: install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: what's changed?
        run: git diff ${{ github.sha }}^ ${{ github.sha }} --name-only '*.md' || exit 0

      - name: run markdownlint on changed files
        run: git diff ${{ github.sha }}^ ${{ github.sha }} --name-only '*.md' | xargs markdownlint
