name: osu-wiki continuous integration

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: markdownlint (changed files)
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # fetch commit before merge, so we can diff

      - name: setup node
        uses: actions/setup-node@v1

      - name: install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: what's changed?
        run: git diff ${GITHUB_SHA}^ ${GITHUB_SHA} --name-only -- *.md

      - name: run markdownlint on changed files
        run: git diff ${GITHUB_SHA}^ ${GITHUB_SHA} --name-only -- *.md | xargs markdownlint
