name: osu-wiki continuous integration

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: markdownlint (changed files)
    runs-on: ubuntu-latest
    steps:
      - name: sparse checkout
        shell: bash
        run: |
          REPOSITORY="https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git"
          BRANCH="${GITHUB_REF/#refs\/heads\//}"

          git version
          git clone --filter=blob:none --no-checkout ${REPOSITORY} .
          git config --local gc.auto 0

          git sparse-checkout init
          git sparse-checkout set '**/*.md' '**/.remark*' '**/*.json'

          git -c protocol.version=2 fetch --no-tags --prune --progress --depth=2 origin +${GITHUB_SHA}:refs/remotes/origin/${BRANCH}
          git checkout --progress --force -B $BRANCH refs/remotes/origin/$BRANCH

      - name: setup node
        uses: actions/setup-node@v1

      - name: install remark dependencies
        run: npm install

      - name: what's changed?
        run: git diff ${{ github.sha }}^ ${{ github.sha }} --name-only '*.md' || exit 0

      - name: run remark on changed files
        run: git diff ${{ github.sha }}^ ${{ github.sha }} --name-only '*.md' | xargs npx remark
